import React, { useEffect, useState } from "react"
import Layout from "@components/layout/layout"
import Header from "@components/header/header"
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css'
//import styles from '../styles/Home.module.css'

export default function HomePage () {
  
  const [productsList, setProductList] = useState([])

  // useEffect (() => {
  //     fetch('/api/avo')
  //     .then(response => response.json())
  //     .then(response => setProductList(response.data))
  // }, [])

  return (
    <div className="container" >
      <Head>
        <title>Store using NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avocado.ico" />
      </Head>

      <Layout>
        <Header/>
        {/* <ProductList products={productsList}/> */}
      </Layout>
    </div>
  )
}